events {}

http {
    log_format audit '$time_local | $remote_addr | $request | status=$status';
    access_log /dev/stdout audit;

    server {
        listen 8443 ssl;

        ssl_certificate     /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://host.docker.internal:8333;
            proxy_set_header Host $http_host;
        }
    }
}
